- rest:
    openApi:
      missingOperation: mock
      specification: ${{ values.api_id }}-api.json
- route:
    id: sample-route
    from:
      uri: direct:someOperationId
      parameters: {}
      steps:
        - log:
            message: "${body}"
        - setBody:
            simple: '{"received": true }'
